# connection {
PORT_FOR_NODES = 89
PORT_FOR_CLIENTS = 233

MAX_NODES_CONNECTION = 50
MAX_CLIENTS_CONNECTION = 50

SOCKET_ACCEPT_TIMEOUT = 0.1
SOCKET_RECEIVE_TIMEOUT = 0.1
# }


# proof of work{
MAX_NONCE = 2 ** 32  # 4 billion
PROOF_OF_WORK_CHECK_BLOCK_FREQUENCY = 10000
# }

#encription {
KEY_BIT_LEN = 64
# }

# block {
MAX_LEN_OF_LIST_OF_NEW_USERS = 50
MAX_LEN_OF_LIST_OF_TRANSACTIONS = 50
# }
